
/**
 * Webpack config helper for JWT Edge Runtime compatibility
 * This file is automatically generated - do not edit
 */
module.exports = {
  /**
   * Apply JWT fixes to webpack config
   */
  applyJwtFixes: function(config) {
    if (!config.resolve) config.resolve = {};
    if (!config.resolve.alias) config.resolve.alias = {};
    
    // Add aliases for problematic jsonwebtoken modules
    config.resolve.alias['jsonwebtoken/lib/asymmetricKeyDetailsSupported'] = require.resolve('./node_modules/jsonwebtoken/lib/asymmetricKeyDetailsSupported.js.next-shim');
    config.resolve.alias['jsonwebtoken/lib/psSupported'] = require.resolve('./node_modules/jsonwebtoken/lib/psSupported.js.next-shim');
    config.resolve.alias['jsonwebtoken/lib/rsaPssKeyDetailsSupported'] = require.resolve('./node_modules/jsonwebtoken/lib/rsaPssKeyDetailsSupported.js.next-shim');
    
    return config;
  }
};
