
/**
 * Webpack config helper for JWT Edge Runtime compatibility
 * This file is automatically generated - do not edit
 */
module.exports = {
  /**
   * Apply JWT fixes to webpack config
   */
  applyJwtFixes: function(config) {
    if (!config.resolve) config.resolve = {};
    if (!config.resolve.alias) config.resolve.alias = {};
    
    // Add aliases for problematic jsonwebtoken modules
    const path = require('path');
    const jsonwebtokenLibPath = path.resolve(process.cwd(), 'node_modules/jsonwebtoken/lib');
    
    config.resolve.alias['jsonwebtoken/lib/asymmetricKeyDetailsSupported'] = path.join(jsonwebtokenLibPath, 'asymmetricKeyDetailsSupported.js.next-shim');
    config.resolve.alias['jsonwebtoken/lib/psSupported'] = path.join(jsonwebtokenLibPath, 'psSupported.js.next-shim');
    config.resolve.alias['jsonwebtoken/lib/rsaPssKeyDetailsSupported'] = path.join(jsonwebtokenLibPath, 'rsaPssKeyDetailsSupported.js.next-shim');
    
    return config;
  }
};
